version: '3.8'

services:
  db:
    image: postgres:14.0-bullseye
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    build:
      context: books_db
      args:
        PROJECT_NAME: books_db
    ports:
      - "127.0.0.1:8080:8080"
    entrypoint: ["java", "-jar", "/usr/local/lib/books_db.jar"]  # Specify entrypoint here
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/book_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db